### ISSUE TITLE
Error on paymentDidComplete

### ISSUE THREAD

**Issue by ericpolkadoc** [AppWerft/Ti.Paypal#4] opened 2016-08-25 19:11 UTC
Hi there,

when the listener for "paymentDidComplete" fires its crashing my app.  

Error from console here:

[ERROR] JNIUtil: !!! Unable to convert unknown Java object class 'org.json.JSONObject' to Js value !!!
[WARN]  W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
[WARN]  W/google-breakpad: Chrome build fingerprint:
[WARN]  W/google-breakpad: 4.0.3
[WARN]  W/google-breakpad: 1
[WARN]  W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
[INFO]  libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 29081 (KrollRuntimeThr)
[INFO]  Timeline: Timeline: Activity_idle id: android.os.BinderProxy@bbce52e time:347486081

No error on "paymentDidCancel" listener.  

If there's any way you can look into a fix that would be great.  

Thanks!

**Comment by AppWerft** [comment] 2016-08-25 19:55
Thanks for the worth hint! I will look tomorrow into and will figure out.

**Comment by AppWerft** [comment] 2016-08-26 12:23
Please try new version. I have tried to convert the JSONObject from PayPal to KrollDict. If this failes I can build a version with strigification of result thes will works annyway.

**Comment by ericpolkadoc** [comment] 2016-08-26 16:51
Hi --

Installed the updated module, however Im receiving a new error message when clicking the button to show the Paypal overlay.  Error message first, then code, let me know if you see that Im doing something incorrectly.

thanks!

[WARN]  W/System.err: java.lang.NullPointerException: Attempt to read from field 'int java.math.BigDecimal.scale' on a null object reference
[WARN]  W/System.err: 	at java.math.BigDecimal.add(BigDecimal.java:733)
[WARN]  W/System.err: 	at de.appwerft.paypal.PaymentProxy.getStuffToBuy(PaymentProxy.java:311)
[WARN]  W/System.err: 	at de.appwerft.paypal.PaymentProxy.showPaymentOverLay(PaymentProxy.java:89)
[WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN]  W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[WARN]  W/System.err: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:918)
[WARN]  W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1141)
[WARN]  W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:356)
[WARN]  W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN]  W/System.err: 	at android.os.Looper.loop(Looper.java:145)
[WARN]  W/System.err: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:118)
[ERROR] TiExceptionHandler: (main) [1188,80928] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,80928] - In undefined:25,17
[ERROR] TiExceptionHandler: (main) [0,80928] - Message: Uncaught Error: Attempt to read from field 'int java.math.BigDecimal.scale' on a null object reference
[ERROR] TiExceptionHandler: (main) [0,80928] - Source:         payment.showPaymentOverLay();
[ERROR] V8Exception: Exception occurred at undefined:25: Uncaught Error: Attempt to read from field 'int java.math.BigDecimal.scale' on a null object reference

```
var PayPal = OS_IOS ? require("ti.paypal") : require("de.appwerft.paypal");

PayPal.initialize({
    clientIdSandbox: "......",
    clientIdProduction: ".....",
    environment: PayPal.ENVIRONMENT_SANDBOX 
});

var item1 = PayPal.createPaymentItem({
    name: "My item",
    price: 15.00,
    sku: "SKU#",
    quantity: 1,
    currency: "USD" 
});

var configuration = PayPal.createConfiguration({
    merchantName: "Lemonaid",
    merchantPrivacyPolicyURL: "http://privacypolicy",
    merchantUserAgreementURL: "http://terms-of-use",
    locale: "en" 
});

var payment = PayPal.createPayment({
    configuration: configuration,
    currencyCode: "USD",
    amount: 15.00, 
    shortDescription: "Order description",
    intent: PayPal.PAYMENT_INTENT_SALE, 
    items: [item1]
});

payment.addEventListener("paymentDidCancel", function(e) {
    console.log("paymentDidCancel");
});

payment.addEventListener("paymentDidComplete", function(e) {
    console.log("paymentDidComplete");
    console.log(e.payment);
});

// adds the button to the view
form.add(createButton("Pay now"));

function createButton(title) {
  var btn = Ti.UI.createButton({
    title: title,
    width: 300,
    color: "#fff",
    height: 40,
    backgroundColor: "#333",
    top: 40
  });
  
  btn.addEventListener("click", openPayment);
  
  return btn;
}

function openPayment()
{
  payment.showPaymentOverLay(); 
}
```

**Comment by AppWerft** [comment] 2016-08-27 08:24
Thank you for detailed report, this helps a lot.
The issue is near price. but line 311 is nothing and the method `scale` I don't see. I will go into the code.

Ok, the issue is inside the price collector, I have added a lot of log lines. Additional I have preset all sizes to 0 (tax, shipping …). New version is commited.

**Comment by AppWerft** [comment] 2016-08-27 08:50
This are the default:
```java
public PaymentItem() {
		this.name = "no name";
		this.sku = "no sku";
		this.quantity = 1;
		this.price = new BigDecimal(0);
		this.currency = "USD";
}
```

**Comment by ericpolkadoc** [comment] 2016-08-31 19:41
The app is all set now -- v1.1.3 changes are working great and I can get the payment response.

I think we just need to turn off the logcat?

**Comment by AppWerft** [comment] 2016-09-01 07:07
done.

**Comment by AppWerft** [comment] 2017-01-03 09:57
Is fixed with last version

**Closed by AppWerft** 2017-01-03 09:57 UTC
